/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace RakNet {

using System;
using System.Runtime.InteropServices;

public class TeamSelection : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TeamSelection(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(TeamSelection obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~TeamSelection() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          RakNetPINVOKE.CSharp_delete_TeamSelection(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public TeamSelection() : this(RakNetPINVOKE.CSharp_new_TeamSelection__SWIG_0(), true) {
  }

  public TeamSelection(JoinTeamType itt) : this(RakNetPINVOKE.CSharp_new_TeamSelection__SWIG_1((int)itt), true) {
  }

  public TeamSelection(JoinTeamType itt, TM_Team param) : this(RakNetPINVOKE.CSharp_new_TeamSelection__SWIG_2((int)itt, TM_Team.getCPtr(param)), true) {
  }

  public TeamSelection(JoinTeamType itt, byte param) : this(RakNetPINVOKE.CSharp_new_TeamSelection__SWIG_3((int)itt, param), true) {
  }

  public JoinTeamType joinTeamType {
    set {
      RakNetPINVOKE.CSharp_TeamSelection_joinTeamType_set(swigCPtr, (int)value);
    } 
    get {
      JoinTeamType ret = (JoinTeamType)RakNetPINVOKE.CSharp_TeamSelection_joinTeamType_get(swigCPtr);
      return ret;
    } 
  }

  public static TeamSelection AnyAvailable() {
    TeamSelection ret = new TeamSelection(RakNetPINVOKE.CSharp_TeamSelection_AnyAvailable(), true);
    return ret;
  }

  public static TeamSelection SpecificTeam(TM_Team specificTeamToJoin) {
    TeamSelection ret = new TeamSelection(RakNetPINVOKE.CSharp_TeamSelection_SpecificTeam(TM_Team.getCPtr(specificTeamToJoin)), true);
    return ret;
  }

  public static TeamSelection NoTeam(byte noTeamSubcategory) {
    TeamSelection ret = new TeamSelection(RakNetPINVOKE.CSharp_TeamSelection_NoTeam(noTeamSubcategory), true);
    return ret;
  }

}

}
